sudo: true
services:
  - docker
cache:
  directories:
    - node_modules
notifications:
  email: true
language: node_js
node_js:
  - '10'
# before_install:
#   - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - npm run docker:build:prod-canary
  - npm run docker:build:test-canary
script:
  - docker run docker:test:canary
deploy:
  provider: script
  script:
  - npm run docker:login
  - npm run docker:release:canary
  on:
    branch: master
